### ISSUE TITLE
Error message when creating task

### ISSUE THREAD

**Issue by Elena-Polyakova** [Ibrahim-Torabek/WETRA_Web#67]
When button Save clicked the system shows Error message. Though it notifies that it was created and after the pop-up window closed, I the task displays in the calendar despite that Error message. So it's unclear why that error message appears.

**Comment by Ibrahim-Torabek** [comment]
I didn't encounter that kind of error. Re-open the issue if you get it again, and specify why it happened.

**Comment by Ibrahim-Torabek** [comment]
Yes It happened
