### ISSUE TITLE
Identify approved request for time off on the calendar

### ISSUE THREAD

**Issue by Elena-Polyakova** [Ibrahim-Torabek/WETRA_Web#75]
If the request for time off was approved by the admin, it has to be identified on the admin's calendar. For now the task just changes its colour to grey. And if pressed, the pop-up window opens again to allow admin to choose what he wants.

**Comment by Ibrahim-Torabek** [comment]
Yes, changing color to grey means task completed or approved time-off. If the task has been double-checked, it means the task was completed. If has a timed trash can, it means the time-off request is approved.
