### ISSUE TITLE
Notify admin that he rejected the request for time off.

### ISSUE THREAD

**Issue by Elena-Polyakova** [Ibrahim-Torabek/WETRA_Web#78]
When time off requested by user for the task was rejected by admin, it becomes available as the time off wasn’t requested at all. So admin will not know if he already rejected the time off. And by pressing on the task it'll show the dialog window again to choose between Reject, Edit, or Confirm.

**Comment by Ibrahim-Torabek** [comment]
Yes, rejected means setting the requested task as normal. I designed it like that.
